cd ./APE_net || exit
/opt/venv/bin/python run_model_online.py || exit
cd .. || exit
cd ./load_estimation || exit
/opt/venv/bin/python run_model_online.py || exit
cd .. || exit
cd ./total_load || exit
/opt/venv/bin/python run_model_online.py || exit
cd .. || exit
cd ./lv_load || exit
/opt/venv/bin/python run_model_online.py || exit
